# Generated by Django 5.2.11 on 2026-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_gst_invoices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-generated_at"]},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["monthly_price"]},
        ),
        migrations.AlterField(
            model_name="organizationsubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
