# Generated by Django 5.2.11 on 2026-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_invoice_options_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsubscription",
            name="expired_notice_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="grace_period_days",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="reminder_sent_1_day_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="reminder_sent_3_days_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
