# Generated by Django 4.2.23 on 2026-02-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_announcement_organization_and_more'),
        ('billing', '0007_alter_bankdetails_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organizationbillingprofile',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
    ]
