# Generated by Django 5.2.11 on 2026-02-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organizationdomain"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organizationdomain",
            new_name="core_organi_organiz_2e4965_idx",
            old_name="core_orgdomain_primary_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationdomain",
            new_name="core_organi_domain__d8c0e7_idx",
            old_name="core_orgdomain_domain_idx",
        ),
    ]
