# Generated by Django 4.2.23 on 2026-02-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enforce_organization_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organizationdomain',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
    ]
