# Generated by Django 5.2.11 on 2026-02-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_auditlog_core_auditl_organiz_c0dcbd_idx_and_more"),
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competency",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="competency",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeecompetency",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeekra",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="keyresult",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="keyresultarea",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="keyresultarea",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="okrobjective",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="performancecycle",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="reviewfeedback",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrecommendation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
    ]
