# Generated by Django 5.2.11 on 2026-02-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("core", "0005_remove_auditlog_core_auditl_organiz_c0dcbd_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="consentrecord",
            name="compliance__organiz_5b7c03_idx",
        ),
        migrations.RemoveIndex(
            model_name="dataretentionpolicy",
            name="compliance__organiz_d132b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="legalhold",
            name="compliance__organiz_53e941_idx",
        ),
        migrations.AlterField(
            model_name="auditexportrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="dataretentionpolicy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="datasubjectrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="legalhold",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="retentionexecution",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
    ]
