# Generated by GitHub Copilot GPT-5.1-Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
