# Generated by Django 5.2.11 on 2026-02-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abac", "0001_initial"),
        ("core", "0005_remove_auditlog_core_auditl_organiz_c0dcbd_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attributetype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="grouppolicy",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attributetype",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="grouppolicy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="policylog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="userpolicy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="grouppolicy",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="policy",
            name="code",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="policy",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="userpolicy",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name="attributetype",
            unique_together={("organization", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="grouppolicy",
            unique_together={("organization", "group_type", "group_value")},
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("organization", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="policy",
            unique_together={("organization", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "code")},
        ),
    ]
