# Generated by Django 4.2.23 on 2026-02-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_announcement_organization_and_more'),
        ('abac', '0002_alter_attributetype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='grouppolicy',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='policylog',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
    ]
