# Generated by Django 4.2.23 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancepunch_faceembedding_fraudlog_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancepunch",
            index=models.Index(
                fields=["organization", "punch_time"], name="att_punch_org_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["organization", "date"], name="att_org_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["organization", "employee", "date"], name="att_org_emp_date_idx"
            ),
        ),
    ]
