# Generated by Django 4.2.23 on 2026-02-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_announcement_organization_and_more'),
        ('attendance', '0004_attendancepunch_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepunch',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='fraudlog',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
    ]
