# Generated by Django 4.2.23 on 2026-02-19 06:54

from django.db import migrations, models
import django.db.models.deletion


def backfill_workflows_organization(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    User = apps.get_model("authentication", "User")
    OrganizationUser = apps.get_model("authentication", "OrganizationUser")
    Employee = apps.get_model("employees", "Employee")
    WorkflowDefinition = apps.get_model("workflows", "WorkflowDefinition")
    WorkflowStep = apps.get_model("workflows", "WorkflowStep")
    WorkflowInstance = apps.get_model("workflows", "WorkflowInstance")
    WorkflowAction = apps.get_model("workflows", "WorkflowAction")

    default_org_id = Organization.objects.order_by("created_at").values_list("id", flat=True).first()

    def user_org_id(user_id):
        if not user_id:
            return None
        membership = OrganizationUser.objects.filter(
            user_id=user_id,
            is_active=True
        ).order_by("-created_at").first()
        if membership and membership.organization_id:
            return membership.organization_id

        return User.objects.filter(id=user_id).values_list("organization_id", flat=True).first()

    def employee_org_id(employee_id):
        if not employee_id:
            return None
        return Employee.objects.filter(id=employee_id).values_list("organization_id", flat=True).first()

    for obj in WorkflowDefinition.objects.filter(organization__isnull=True).iterator():
        org_id = user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            WorkflowDefinition.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in WorkflowStep.objects.filter(organization__isnull=True).iterator():
        workflow_org_id = WorkflowDefinition.objects.filter(id=obj.workflow_id).values_list("organization_id", flat=True).first()
        org_id = workflow_org_id or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            WorkflowStep.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in WorkflowInstance.objects.filter(organization__isnull=True).iterator():
        workflow_org_id = WorkflowDefinition.objects.filter(id=obj.workflow_id).values_list("organization_id", flat=True).first()
        approver_org_id = employee_org_id(obj.current_approver_id)
        org_id = workflow_org_id or approver_org_id or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            WorkflowInstance.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in WorkflowAction.objects.filter(organization__isnull=True).iterator():
        instance_org_id = WorkflowInstance.objects.filter(id=obj.instance_id).values_list("organization_id", flat=True).first()
        actor_org_id = employee_org_id(obj.actor_id)
        org_id = instance_org_id or actor_org_id or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            WorkflowAction.objects.filter(pk=obj.pk).update(organization_id=org_id)


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_convert_org_uuid_to_fk"),
        (
            "core",
            "0002_rename_core_announ_organiz_2721f4_idx_core_announ_organiz_f158c6_idx_and_more",
        ),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_workflows_organization, reverse_noop),
        migrations.AlterField(
            model_name="workflowaction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["organization", "created_at"],
                name="workflows_w_organiz_6ca38d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(
                fields=["organization", "created_at"],
                name="workflows_w_organiz_ef2d2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["organization", "created_at"],
                name="workflows_w_organiz_82007f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstep",
            index=models.Index(
                fields=["organization", "created_at"],
                name="workflows_w_organiz_b88c8a_idx",
            ),
        ),
    ]
