"""
Core Middleware
Schema-safe, ASGI-safe, Production-ready
"""

import logging
import uuid
import re
import time
from typing import Optional
from django.http import JsonResponse, HttpRequest, HttpResponse
from django.utils.deprecation import MiddlewareMixin
from django.core.exceptions import ValidationError
from apps.core.logging import set_correlation_id

from .context import (
    set_client_ip,
    set_user_agent,
    set_device_id,
)

logger = logging.getLogger(__name__)


# =============================================================================
# Helpers
# =============================================================================

def is_schema_request(request: HttpRequest) -> bool:
    """
    True when request is generated by drf-spectacular
    """
    return getattr(request, "swagger_fake_view", False)


# =============================================================================
# AUDIT & REQUEST METADATA
# =============================================================================

class AuditMiddleware(MiddlewareMixin):
    """
    Capture request metadata for auditing.
    """

    def process_request(self, request: HttpRequest) -> Optional[HttpResponse]:
        if is_schema_request(request):
            return None

        x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            ip = x_forwarded_for.split(",")[0].strip()
        else:
            ip = request.META.get("REMOTE_ADDR", "")

        user_agent = request.META.get("HTTP_USER_AGENT", "")
        device_id = request.META.get("HTTP_X_DEVICE_ID", "")

        request.client_ip = ip
        request.user_agent = user_agent
        request.device_id = device_id

        set_client_ip(ip)
        set_user_agent(user_agent)
        set_device_id(device_id)

        return None


# =============================================================================
# INPUT SANITIZATION
# =============================================================================

class InputSanitizationMiddleware(MiddlewareMixin):
    """
    XSS / injection guard for write requests.
    Checks both form-encoded POST data AND JSON request bodies.
    """

    _pattern = re.compile(r"<script|onerror|onload|javascript:", re.IGNORECASE)

    def process_request(self, request: HttpRequest) -> Optional[HttpResponse]:
        if is_schema_request(request):
            return None

        if request.method not in ("POST", "PUT", "PATCH"):
            return None

        # 1. Check form-encoded POST data
        try:
            for key, value in request.POST.items():
                if isinstance(value, str) and self._pattern.search(value):
                    raise ValidationError(
                        f"Invalid input detected in field: {key}"
                    )
        except Exception:
            pass

        # 2. Check JSON body
        content_type = request.content_type or ""
        if "json" in content_type:
            try:
                import json
                body = request.body
                if body:
                    data = json.loads(body)
                    self._scan_json(data)
            except (json.JSONDecodeError, UnicodeDecodeError):
                pass  # Let DRF handle malformed JSON
            except ValidationError:
                raise  # Re-raise our own validation errors

        return None

    def _scan_json(self, data, path=""):
        """Recursively scan JSON data for XSS patterns."""
        if isinstance(data, dict):
            for key, value in data.items():
                field_path = f"{path}.{key}" if path else key
                if isinstance(value, str) and self._pattern.search(value):
                    raise ValidationError(
                        f"Invalid input detected in field: {field_path}"
                    )
                self._scan_json(value, field_path)
        elif isinstance(data, list):
            for i, item in enumerate(data):
                self._scan_json(item, f"{path}[{i}]")


# =============================================================================
# CORRELATION ID
# =============================================================================

class CorrelationIdMiddleware:
    """
    Adds X-Correlation-ID header and context.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        if is_schema_request(request):
            return self.get_response(request)

        correlation_id = request.headers.get(
            "X-Correlation-ID", str(uuid.uuid4())
        )

        set_correlation_id(correlation_id)

        response = self.get_response(request)
        response["X-Correlation-ID"] = correlation_id
        return response


# =============================================================================
# REQUEST ID
# =============================================================================

class RequestIDMiddleware:
    """
    Adds X-Request-ID header.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        if is_schema_request(request):
            return self.get_response(request)

        request_id = request.headers.get(
            "X-Request-ID", str(uuid.uuid4())
        )
        request.request_id = request_id

        response = self.get_response(request)
        response["X-Request-ID"] = request_id
        return response


# =============================================================================
# METRICS / LATENCY
# =============================================================================

class MetricsMiddleware:
    """
    Logs request latency and status.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        if is_schema_request(request):
            return self.get_response(request)

        start = time.monotonic()
        response = self.get_response(request)
        duration_ms = int((time.monotonic() - start) * 1000)

        user = getattr(request, "user", None)

        logger.info(
            "request_metrics method=%s path=%s status=%s duration_ms=%s user_id=%s",
            request.method,
            request.path,
            response.status_code,
            duration_ms,
            getattr(user, "id", None),
        )

        response["X-Response-Time-ms"] = str(duration_ms)
        return response


# =============================================================================
# SECURITY HEADERS
# =============================================================================

class SecurityHeadersMiddleware(MiddlewareMixin):
    """
    Adds security headers to responses.
    """

    def process_response(
        self, request: HttpRequest, response: HttpResponse
    ) -> HttpResponse:

        if is_schema_request(request):
            return response

        # Content Security Policy
        if (
            request.path.startswith("/admin")
            or request.path.startswith("/api/docs")
            or request.path.startswith("/api/redoc")
        ):
            response["Content-Security-Policy"] = (
                "default-src 'self' 'unsafe-inline'; "
                "script-src 'self' 'unsafe-inline'; "
                "style-src 'self' 'unsafe-inline'; "
                "img-src 'self' data:; "
                "font-src 'self' data:; "
                "frame-ancestors 'none'"
            )
        else:
            response["Content-Security-Policy"] = (
                "default-src 'self'; frame-ancestors 'none'"
            )

        response["X-Content-Type-Options"] = "nosniff"
        response["X-XSS-Protection"] = "1; mode=block"
        response["X-Frame-Options"] = "DENY"
        response["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response["Permissions-Policy"] = (
            "geolocation=(self), camera=(self), microphone=(self)"
        )

        return response


# =============================================================================
# BRANCH CONTEXT MIDDLEWARE
# =============================================================================

class BranchContextMiddleware:
    """
    Safe placeholder Branch Context middleware.

    Branch logic can be expanded later.
    This MUST exist to satisfy Django middleware loading.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        # Do nothing for now (safe)
        return self.get_response(request)
