# Generated by Django 4.2.23 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="rpt_exec_org_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["requested_by", "status", "created_at"],
                name="rpt_exec_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["template", "status", "created_at"],
                name="rpt_exec_tpl_status_idx",
            ),
        ),
    ]
