# Generated by Django 4.2.23 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_certification_document_emergencycontact_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "employment_status", "is_active"],
                name="emp_org_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "department"], name="emp_org_dept_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "designation"], name="emp_org_desig_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "location"], name="emp_org_loc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "reporting_manager"], name="emp_org_mgr_idx"
            ),
        ),
    ]
