# Generated by Django 5.2.11 on 2026-02-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_auditlog_core_auditl_organiz_c0dcbd_idx_and_more"),
        ("employees", "0004_employee_emp_org_status_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeeaddress",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeebankaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeedependent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeepromotion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeeskill",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employeetransfer",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="employmenthistory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="exitinterview",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="resignationrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="separationchecklist",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this record belongs to (primary isolation key)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
    ]
