# Generated by Django 4.2.23 on 2026-02-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_announcement_organization_and_more'),
        ('employees', '0005_alter_certification_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeeaddress',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeepromotion',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeetransfer',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='separationchecklist',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='organization',
            field=models.ForeignKey(help_text='Organization this record belongs to (primary isolation key)', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization'),
        ),
    ]
