# Generated by Django 5.2.11 on 2026-02-08 10:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, help_text='Organization this session belongs to', null=True)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Full JWT refresh token')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='authenticat_organiz_1fed11_idx',
            old_name='authenticat_organiz_91ea80_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='authenticat_organiz_9eaf5f_idx',
            old_name='authenticat_organiz_6ec5c1_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='authenticat_organiz_3f6976_idx',
            old_name='authenticat_organiz_181dbb_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[1-9]\\d{6,14}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy username (optional, not used for login)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization_id', 'is_active'], name='branches_organiz_8da68f_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['name', 'is_active'], name='branches_name_3c7ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='branchuser',
            index=models.Index(fields=['user', 'is_active'], name='branch_user_user_id_467177_idx'),
        ),
        migrations.AddIndex(
            model_name='branchuser',
            index=models.Index(fields=['branch', 'role', 'is_active'], name='branch_user_branch__de6748_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_5200f6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization_id', 'role', 'is_active'], name='organizatio_organiz_a637ab_idx'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['organization_id', 'user', 'is_active'], name='authenticat_organiz_139cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_f427c8_idx'),
        ),
    ]
