# Generated by Django 5.2.11 on 2026-02-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_convert_org_uuid_to_fk"),
        ("core", "0005_remove_auditlog_core_auditl_organiz_c0dcbd_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usersession",
            name="authenticat_organiz_139cd6_idx",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="organization_id",
        ),
        migrations.AddField(
            model_name="usersession",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this session belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["organization", "user", "is_active"],
                name="authenticat_organiz_139cd6_idx",
            ),
        ),
    ]
