# Generated by Django 4.2.23 on 2026-02-19 06:54

from django.db import migrations, models
import django.db.models.deletion


def backfill_ai_services_organization(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    User = apps.get_model("authentication", "User")
    OrganizationUser = apps.get_model("authentication", "OrganizationUser")
    Employee = apps.get_model("employees", "Employee")
    AIModelVersion = apps.get_model("ai_services", "AIModelVersion")
    AIPrediction = apps.get_model("ai_services", "AIPrediction")

    default_org_id = Organization.objects.order_by("created_at").values_list("id", flat=True).first()

    def user_org_id(user_id):
        if not user_id:
            return None
        membership = OrganizationUser.objects.filter(
            user_id=user_id,
            is_active=True
        ).order_by("-created_at").first()
        if membership and membership.organization_id:
            return membership.organization_id

        return User.objects.filter(id=user_id).values_list("organization_id", flat=True).first()

    def employee_org_id(employee_id):
        if not employee_id:
            return None
        return Employee.objects.filter(id=employee_id).values_list("organization_id", flat=True).first()

    for obj in AIModelVersion.objects.filter(organization__isnull=True).iterator():
        org_id = user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            AIModelVersion.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in AIPrediction.objects.filter(organization__isnull=True).iterator():
        model_org_id = AIModelVersion.objects.filter(id=obj.model_version_id).values_list("organization_id", flat=True).first()
        reviewer_org_id = employee_org_id(obj.reviewed_by_id)
        org_id = model_org_id or reviewer_org_id or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            AIPrediction.objects.filter(pk=obj.pk).update(organization_id=org_id)


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_convert_org_uuid_to_fk"),
        (
            "core",
            "0002_rename_core_announ_organiz_2721f4_idx_core_announ_organiz_f158c6_idx_and_more",
        ),
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_ai_services_organization, reverse_noop),
        migrations.AlterField(
            model_name="aimodelversion",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="aiprediction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelversion",
            index=models.Index(
                fields=["organization", "created_at"],
                name="ai_services_organiz_9552d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiprediction",
            index=models.Index(
                fields=["organization", "created_at"],
                name="ai_services_organiz_6bffef_idx",
            ),
        ),
    ]
