# Generated by Django 4.2.23 on 2026-02-19 06:54

from django.db import migrations, models
import django.db.models.deletion


def backfill_chat_organization(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    User = apps.get_model("authentication", "User")
    OrganizationUser = apps.get_model("authentication", "OrganizationUser")
    Conversation = apps.get_model("chat", "Conversation")
    ConversationParticipant = apps.get_model("chat", "ConversationParticipant")
    Message = apps.get_model("chat", "Message")
    MessageReaction = apps.get_model("chat", "MessageReaction")

    default_org_id = Organization.objects.order_by("created_at").values_list("id", flat=True).first()

    def user_org_id(user_id):
        if not user_id:
            return None
        membership = OrganizationUser.objects.filter(
            user_id=user_id,
            is_active=True
        ).order_by("-created_at").first()
        if membership and membership.organization_id:
            return membership.organization_id

        return User.objects.filter(id=user_id).values_list("organization_id", flat=True).first()

    for obj in Conversation.objects.filter(organization__isnull=True).iterator():
        org_id = user_org_id(obj.created_by_id)
        if not org_id:
            first_participant = ConversationParticipant.objects.filter(
                conversation_id=obj.id
            ).values_list("user_id", flat=True).first()
            org_id = user_org_id(first_participant)
        org_id = org_id or default_org_id
        if org_id:
            Conversation.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in ConversationParticipant.objects.filter(organization__isnull=True).iterator():
        conversation_org_id = Conversation.objects.filter(id=obj.conversation_id).values_list("organization_id", flat=True).first()
        org_id = conversation_org_id or user_org_id(obj.user_id) or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            ConversationParticipant.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in Message.objects.filter(organization__isnull=True).iterator():
        conversation_org_id = Conversation.objects.filter(id=obj.conversation_id).values_list("organization_id", flat=True).first()
        org_id = conversation_org_id or user_org_id(obj.sender_id) or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            Message.objects.filter(pk=obj.pk).update(organization_id=org_id)

    for obj in MessageReaction.objects.filter(organization__isnull=True).iterator():
        message_org_id = Message.objects.filter(id=obj.message_id).values_list("organization_id", flat=True).first()
        org_id = message_org_id or user_org_id(obj.user_id) or user_org_id(obj.created_by_id) or default_org_id
        if org_id:
            MessageReaction.objects.filter(pk=obj.pk).update(organization_id=org_id)


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_convert_org_uuid_to_fk"),
        (
            "core",
            "0002_rename_core_announ_organiz_2721f4_idx_core_announ_organiz_f158c6_idx_and_more",
        ),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_chat_organization, reverse_noop),
        migrations.AlterField(
            model_name="conversation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="conversationparticipant",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="messagereaction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["organization", "created_at"],
                name="chat_conver_organiz_38dd6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "created_at"],
                name="chat_messag_organiz_123b28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["organization", "created_at"],
                name="chat_messag_organiz_b77086_idx",
            ),
        ),
    ]
